@isTest

Private Class CP_MarketForecast_Test{
    static testMethod void Method1(){
    
        /*
    
        Account acc = new Account(Name='Test Account');
        Insert acc;
        
       
        List<loan__c> insertloan = new List<loan__c>();
        Loan__c ln = new Loan__c(Originator__c = acc.id, zip_code__c = '90266', address__c = 'test now', As_is_valuation__c = 1000, Borrower_Name__c='Test Borrower');
        Loan__c ln1 = new Loan__c(Originator__c = acc.id, address__c = 'test ninja', As_is_valuation__c = 5000);
        insertloan.add(ln);
        insertloan.add(ln1);
        insert insertloan;
        
        
        Test.StartTest();

        PageReference pageRef = Page.CP_SubMarketForecast;
        pageRef.getParameters().put('id',ln.id);
        pageRef.getParameters().put('retURL','www.google.com');
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardSetController StandardsObjectController = new ApexPages.StandardSetController(insertloan);//TestExamples);
        StandardsObjectController.setSelected(insertloan);
        
        CP_SubMarketForecast gi = new CP_SubMarketForecast(StandardsObjectController);
        gi.Getresults();
        gi.BackToList();
        
        
        

        PageReference pageRef1 = Page.CP_OFAC;
        pageRef1.getParameters().put('id',ln.id);
        pageRef1.getParameters().put('retURL','www.google.com');
        Test.setCurrentPageReference(pageRef1);
        ApexPages.StandardSetController StandardsObjectController1 = new ApexPages.StandardSetController(insertloan);//TestExamples);
        StandardsObjectController1.setSelected(insertloan);
        
        CP_OFAC gi1 = new CP_OFAC(StandardsObjectController1);
        gi1.Getresults();
        gi1.BackToList();
        Test.StopTest();

        */
    }
}